name: Test and Lint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 12
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Install
      run: npm i
    - name: Lint
      run: npm run lint
    - name: Test
      run: npm run test
